### ISSUE TITLE
Crashes on compilation error

### ISSUE THREAD

**Issue by cmer** [sdball/coffee-taster#1]
When CoffeeScript compilation fails (ie: invalid syntax), the watch script crashes.

**Comment by sdball** [comment]
@cmer Thanks for raising the issue. Now if there's a compilation error `rake watch` doesn't crash and an alert JavaScript is compiled.

@yodatravis Thanks for the pull request fixing the rake script.

**Comment by YodaTravis** [comment]
Is it worth a blog post on how to submit a pull request for an open source project on github or is that too over done?

**Comment by sdball** [comment]
Nothing is too overdone. Check out the tag line on rakeroutes :-)

-- Stephen (iPhone)

On Feb 25, 2012, at 2:54 PM, YodaTravis
reply@reply.github.com
wrote:

> Is it worth a blog post on how to submit a pull request for an open source project on github or is that too over done?
>

**Comment by cmer** [comment]
Thanks!

**Comment by cmer** [comment]
This doesn't seem to be fully fixed:

carl@iMac:/tmp/coffee-taster master ✖ $ rake watch
Watching CoffeeScript files in /coffee.
Changes detected, recompiling
Changes detected, recompiling
Changes detected, recompiling
Changes detected, recompiling
Changes detected, recompiling
Changes detected, recompiling
Changes detected, recompiling
Changes detected, recompiling
rake aborted!
update - //private/tmp/coffee-taster/coffee/main.coffee: Parse error on line 8: Unexpected '='

**Comment by sdball** [comment]
Could you include a sample .coffee file that causes this behavior?

**Comment by cmer** [comment]
I wrote:

```
$('.foo').data('bar') = 0
```

which is obviously invalid

**Comment by sdball** [comment]
Just pushed up a fix.

**Comment by cmer** [comment]
dude you're fast, thanks!

**Comment by sdball** [comment]
No problem, glad to help. :-)
